version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    links:
      - database
    ports:
      - $API_PORT:$API_PORT
    environment:
      BASE_IMAGE: $API_BASE_IMAGE
      PORT: $API_PORT
    volumes:
      - .:/api:delegated

  database:
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USERNAME
    image: postgres:13-alpine
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
