default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOSTNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>
  port: <%= ENV["DB_PORT"] %>
  username: <%= ENV["DB_USERNAME"] %>

development:
  <<: *default
  database: curex_development

test:
  <<: *default
  database: curex_test
